### PR TITLE
🩹fix: add missing component demos

### LINKED ISSUE #27: [feat]: can you complete the docs components? like tooltip, switch, toggle, etc...
### Feature description

I want to use this lib, but some documentation not complete filled, like preview & code not showing.

example: https://nyxbui.design/docs/components/switch

### Affected component/components

_No response_

### Additional Context

Additional details here...

### Before submitting

- [X] I've made research efforts and searched the documentation
- [X] I've searched for existing issues and PRs

### PR DESCRIPTION
**Pull request by alexander-cato**
### Overview
This pull request addresses issue #27 by adding missing component demos to the documentation.

### Impact
- All component demos properly registered
- Complete and functional public docs
- Closes #27

### CODE REVIEW

**Review by Admeen3581 — APPROVED** [review]
Thank you I was also noticing this issue and was going to PR it if I didn't have exams. I approve as an _not maintainer_

**Comment by nyxb** [comment]
Oh, I'm sorry I noticed your PR too late I had seen the issue first and added the missing parts. I believe I covered everything. However, I really appreciate that you created this PR and would like to acknowledge your contribution. Perhaps you could take a look at the current main branch and compare it with your changes?

**Comment by alexander-cato** [comment]
@nyxb It appears that some examples were still missing from commit 4246e99, so merging this PR would still be beneficial. For reference, please review the slider, sheet, and skeleton pages.

### Updates Made to This PR
1. **Example Registration Location:** Moved examples that were mistakenly placed in registry-ui to the correct location in registry-examples.
2. **Conflict Resolution:** Merged the latest changes from upstream/main to resolve conflicts.

**Review by nyxb — APPROVED** [review]
Thank you for the additional component examples! The implementation looks great, especially the additions for slider, sheet, and skeleton components are very helpful. Approved!

**Pull request merged**
